"""initial tables

Revision ID: 43dae593767a
Revises: 
Create Date: 2026-06-23 21:06:52.053479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43dae593767a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID статуса'),
    sa.Column('name', sa.Text(), nullable=False, comment='Название статуса'),
    sa.Column('description', sa.Text(), nullable=False, comment='Описание статуса'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID задачи'),
    sa.Column('title', sa.Text(), nullable=False, comment='Свойства задачи'),
    sa.Column('description', sa.Text(), nullable=False, comment='Описание задачи'),
    sa.Column('status', sa.Text(), nullable=False, comment='Статус задачи'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Когда создалась задача'),
    sa.ForeignKeyConstraint(['status'], ['status.name'], name='tasks_status_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('status')
    # ### end Alembic commands ###
